### ISSUE TITLE
Mini app can crash on android devices when development

### ISSUE THREAD

**Issue by VanThuan76** [Telegram-Mini-Apps/nextjs-template#14]
I have trouble with an issue where the app crashes on Android devices. I found your issue from a year ago at https://github.com/Telegram-Mini-Apps/telegram-apps/issues/210, and I followed the guidance there, but it's still not working. Can you explain why? Thank you.

**Comment by heyqbnk** [comment]
Not sure what is the problem. Probably Telegram for Android itself (will not be surprised). Try searching for clues
