### ISSUE TITLE
Is the app router unavailable?

### ISSUE THREAD

**Issue by Mergemat** [Telegram-Mini-Apps/nextjs-template#2]
Hi! I've seen your lib rework and now i don't understand how it will work with app router... Are y planning to add examples for app router?

**Comment by heyqbnk** [comment]
Hey. I don't really have much fresh experience working with Next.js. Could clarify what App Router is?

**Comment by Mergemat** [comment]
> Hey. I don't really have much fresh experience working with Next.js. Could clarify what App Router is?

https://github.com/Telegram-Mini-Apps/nextjs-template/tree/72cf7256284212a239b8711d1f6447246e7c1f4a
thats a prev version of this template, you used app router here. 

in app router there is no 'pages' directory, instead every folder inside 'app/' is a page if it has 'page.tsx' inside. there's a lot of differences tbh

**Comment by NicolasCassunde** [comment]
up

**Comment by heyqbnk** [comment]
Hey! I am currently working on  the template remake using the App Router. I will let you know, when the template is updated

**Comment by heyqbnk** [comment]
Done.

**Comment by Mergemat** [comment]
> Done.

Thats awesome! Thank you very much
