### ISSUE TITLE
Error in outside telegram after Update  @telegram-apps/sdk-react to  "^2.0.19" version

### ISSUE THREAD

**Issue by alireza-asgharii** [Telegram-Mini-Apps/nextjs-template#31]
After I install the **new SDK version** update, I have a problem with the app loading **outside of Telegram**, whereas this did not happen before. In addition, there is no problem inside Telegram.

```
/node_modules/.pnpm/@telegram-apps+sdk-react@2.0.5_@types+react@18.3.3_react@18.3.1/node_modules/@telegram-apps/sdk-react/dist/index.js
Error: ENOENT: no such file or directory, open '/app/node_modules/.pnpm/@telegram-apps+sdk-react@2.0.5_@types+react@18.3.3_react@18.3.1/node_modules/@telegram-apps/sdk-react/dist/index.js'

Import trace for requested module:
./node_modules/.pnpm/@telegram-apps+sdk-react@2.0.5_@types+react@18.3.3_react@18.3.1/node_modules/@telegram-apps/sdk-react/dist/index.js
```

**Comment by heyqbnk** [comment]
Your problem is not related to the environment. The problem is related to the builder, it can't find the package for some reason. Try removing node_modules and installing again

**Comment by alireza-asgharii** [comment]
> Your problem is not related to the environment. The problem is related to the builder, it can't find the package for some reason. Try removing node_modules and installing again

**Comment by alireza-asgharii** [comment]
> Your problem is not related to the environment. The problem is related to the builder, it can't find the package for some reason. Try removing node_modules and installing again


I was able to solve the problem.
I found out that the hook is useTelegramMock.ts, which needs to be added to the config after the update.

You just need to add the value

```
[
"signature",
"SignaturePkdisAdGwQepp8pmdCeUM6k_NKjxU5aiofGrn_SomeRandomSigna-UzResG0mLxuPcQZT5rlnWDw",
],
```

to the initDataRaw array
