### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by alireza-asgharii** [Telegram-Mini-Apps/nextjs-template#32]
Why am I getting this error?

![Screenshot 2024-12-15 174328](https://github.com/user-attachments/assets/c875cc89-c751-4a68-b552-1d4e2d6947ba)

**Comment by alireza-asgharii** [comment]
> Why am I getting this error?
> 
> ![Screenshot 2024-12-15 174328](https://private-user-images.githubusercontent.com/78016989/395868320-c875cc89-c751-4a68-b552-1d4e2d6947ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzI2NzgsIm5iZiI6MTczNDI3MjM3OCwicGF0aCI6Ii83ODAxNjk4OS8zOTU4NjgzMjAtYzg3NWNjODktYzc1MS00YTY4LWI1NTItMWQ0ZTJkNjk0N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE0MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjM2JlZjZjMzc3YjlmM2NkMjBiZDIxN2IzZTllYjQ4YzhlNDk5YjFmYjViMDkwMmIxNWVjMGQ3ZDcyNGQ0ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jGqITLh442Lbow4ootpB0y4wweu3ceU5r0z5P6aiLH0)

This error in all versions from mini app for me. react-template and nextjs-template

**Comment by heyqbnk** [comment]
Is it VSCode? For some reason, it attempts to read tsconfig in node_modules

**Comment by alireza-asgharii** [comment]
> Is it VSCode? For some reason, it attempts to read tsconfig in node_modules

Yes, it is VSCode? why?

**Comment by heyqbnk** [comment]
I don't know, I don't use VSCode. There is no such problem in WebStorm
