### ISSUE TITLE
Error: Unable to retrieve launch parameters from any known source.

### ISSUE THREAD

**Issue by ibitday** [Telegram-Mini-Apps/nextjs-template#5]
when i run this project with follow command, the err occured.

```
yarn
```

```
yarn dev
```

open http://localhost:3000/

**Comment by ibitday** [comment]
> I'm getting the same error, i cloned the repo using this command : npx create-next-app@latest tma-template --use-npm --example "https://github.com/Telegram-Mini-Apps/nextjs-template" and when running the development server, I'm getting Error: Unable to retrieve launch parameters from any known source.

i deploy the project to vercel, and create bot in telegram and set the domain for it, after that, i open the webapp in telegram bot, the same error also not solve.  can you help me? thanks  @heyqbnk

**Comment by heyqbnk** [comment]
You must run the application inside Telegram. In case, you are still having this issue, please, create a reproducible example.

**Comment by heyqbnk** [comment]
I have just checked using the template this way:

1. Press the `Use this template` button and create a new repository on GitHub.
2. Go to the Vercel dashboard and add this repository.
3. Use a default Vercel configuration for the Next project, deploy the project
4. Create a new app in BotFather and specify link, returned by Vercel
5. Open the app

This worked fine for me, I used only GitHub and Vercel interfaces, zero configuration

**Comment by shmlkv** [comment]
To launch an application for local development use some tunnel, like [cloudflared](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-local-tunnel/) and put url in botfather settings.

**Comment by osmanthustonx** [comment]
My user faces this issue in the Telegram web view; after refreshing multiple times, it returns to normal.

Device: iphone 16 pro
OS: ios 18.0.1
Telegram version: 11.3 (29835)

![img_v3_02gd_bc34e3cc-6574-4920-8828-108ceca86chu](https://github.com/user-attachments/assets/518ce6de-aba0-4e81-9f8c-d7d3eb8801c8)

What could be causing this issue?

**Comment by flashgrimmie** [comment]
> My user faces this issue in the Telegram web view; after refreshing multiple times, it returns to normal.
> 
> Device: iphone 16 pro OS: ios 18.0.1 Telegram version: 11.3 (29835)
> 
> ![img_v3_02gd_bc34e3cc-6574-4920-8828-108ceca86chu](https://github.com/user-attachments/assets/518ce6de-aba0-4e81-9f8c-d7d3eb8801c8)
> 
> What could be causing this issue?

did you resolve it?
