### ISSUE TITLE
Next 15 + Tailwind APP Router

### ISSUE THREAD

**Issue by NicolasCassunde** [Telegram-Mini-Apps/nextjs-template#6]
Hey guys, I'm trying to do something like evaa.finance or blum.io, but I'm a bit confused and don't know which SDK to use. Should I use:

- TMA SDK React: https://docs.telegram-mini-apps.com/

- TWA-Dev SDK: https://docs.ton.org/develop/dapps/telegram-apps/app-examples

Can someone help me with this? And please explain to me what the difference is.

**Comment by heyqbnk** [comment]
`@tma.js` is developed and supported by community. `@twa-dev` uses the official Telegram SDK. 

I would recommend using `@tma.js`.
