### ISSUE TITLE
"Please send me a valid url. https is required."

### ISSUE THREAD

**Issue by deuxego** [Telegram-Mini-Apps/nextjs-template#8]
When I send a link like `https://localhost:3000` (obtained from Next.js --experimental-https) to BotFather, I get the following response 
> Please send me the correct url. Requires https.

**Comment by heyqbnk** [comment]
In production, BotFather accepts only https links excluding `localhost`. It could either be some IP

**Comment by heyqbnk** [comment]
Try using `https://127.0.0.1:3000`. Readme was updated

**Comment by Rondos88** [comment]
> Try using `https://127.0.0.1:3000`. Readme was updated

Hi! Now this link not working too. Any issues?
